In [1]:
import numpy as np

# Arrays

In [2]:
a = np.array([[1,2,3],
              [4,5,6]])

In [3]:
a.shape

(2, 3)

In [4]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[0]

1

In [6]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [7]:
a[:3]

array([10,  2,  3])

In [8]:
b = a[3:]
b

array([4, 5, 6])

In [9]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [10]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[1,3]

8

# Array Attributes

In [12]:
a.ndim

2

In [13]:
a.shape

(3, 4)

In [14]:
len(a.shape) == a.ndim

True

In [15]:
a.size

12

In [16]:
import math
a.size == math.prod(a.shape)

True

In [17]:
a.dtype

dtype('int64')

In [18]:
np.zeros(2)

array([0., 0.])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.empty(2)

array([1., 1.])

In [21]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [24]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
x = np.ones(2,dtype = np.int64)
x

array([1, 1])

In [26]:
arr = np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [28]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [30]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
array_example = np.array([[[0,1,4,3],
                           [4,5,2,2]],
                           [[5,6,1,3],
                            [6,2,1,4]],
                            [[5,9,0,1],
                             [6,7,1,2]]])

In [35]:
array_example.ndim

3

In [36]:
array_example.size

24

In [37]:
array_example.shape

(3, 2, 4)

In [39]:
a = np.arange(6)

In [40]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


# Indexing and Slicing

In [41]:
data = np.array([1,2,3])

In [42]:
data[0:2]

array([1, 2])

In [43]:
data[1:]

array([2, 3])

In [44]:
data[-2:]

array([2, 3])

In [49]:
a = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

In [50]:
print(a[a<5])

[1 2 3 4]


In [52]:
five = (a>=5)
print(a[five])

[ 5  6  7  8  9 10 11 12]


# Array Operations

In [53]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)
data+ones

array([2, 3])

In [54]:
data-ones

array([0, 1])

In [55]:
data*ones

array([1, 2])

In [56]:
data/ones

array([1., 2.])

In [57]:
a = np.array([1,2,3,4])
a.sum()

10

In [58]:
a.max()

4

In [59]:
a.min()

1

In [60]:
b = np.array([[1,1],[2,2]])

In [61]:
b.sum(axis=0)

array([3, 3])

In [62]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

In [63]:
data = np.array([1.0,2.0])
data * 1.6

array([1.6, 3.2])

# Matrices

In [64]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
data[0,1]

2

In [66]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [67]:
data[0:2,0]

array([1, 3])

In [68]:
data = np.array([[1,2],[3,4]])
ones = np.array([[1,1],[1,1]])
data + ones

array([[2, 3],
       [4, 5]])

In [69]:
data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.array([[1,1]])
data+ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [70]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

# Getting unique items and Counts

In [71]:
a = np.array([11,11,12,13,14,15,16,17,17,12,13,11,14,18,19,20])

In [72]:
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
unique_values, indices = np.unique(a, return_index=True)
print(indices)

[ 0  2  3  4  5  6  7 13 14 15]


In [75]:
unique_values, occurance_count = np.unique(a,return_counts=True)
print(occurance_count)

[3 2 2 2 1 1 2 1 1 1]


# Transposing and Reshaping

In [76]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [80]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# Reversing and array

In [81]:
arr = np.array([1,2,3,4,5,6,7,8])

In [82]:
reveresed_array = np.flip(arr)

In [83]:
print("Reversed Array: ", reveresed_array)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [84]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [85]:
reveresed_array = np.flip(arr_2d)

In [86]:
print(reveresed_array)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [87]:
reveresed_array_rows = np.flip(arr_2d,axis=0)
print(reveresed_array_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [88]:
reveresed_array_columns = np.flip(arr_2d,axis=1)
print(reveresed_array_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


# Flattening

In [89]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [90]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Save and Load NumPy Objects

In [91]:
a = np.array([1,2,3,4,5,6])

In [92]:
np.save('filename',a)

In [93]:
b = np.load('filename.npy')

In [94]:
b

array([1, 2, 3, 4, 5, 6])

In [95]:
csv_arr = np.array([1,2,3,4,5,6,7,8])

In [96]:
np.savetxt('new_file.csv',csv_arr)

In [97]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Accessing the docstring for more information

In [98]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [99]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [100]:
a = np.array([1,2,3,4,5,6])

In [101]:
a?

Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        ~/anaconda3/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object th

In [102]:
def double(a):
    '''Returns a*2'''
    return a*2

In [103]:
double?

Signature: double(a)
Docstring: Returns a*2
File:      /var/folders/vy/bpb645w940104xm12cdmq4b80000gn/T/ipykernel_36101/2332580270.py
Type:      function

In [104]:
double??

Signature: double(a)
Source:   
def double(a):
    '''Returns a*2'''
    return a*2
File:      /var/folders/vy/bpb645w940104xm12cdmq4b80000gn/T/ipykernel_36101/2332580270.py
Type:      function